services:
  opensearch:
    image: opensearchproject/opensearch:2
    environment:
      discovery.type: single-node
      DISABLE_SECURITY_PLUGIN: true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
